sonar.verbose=true
sonar.organization=nik01key
sonar.projectKey=nik01key_saidemytrend
sonar.projectName=saidemytrend
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources=
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

